"""Dados fictícios de demonstração para testes e interface."""

from __future__ import annotations


DEMO_COMPANIES = [
    {
        "company_id": "KZD-001",
        "company_name": "Kwanza Distribuição, Lda.",
        "nif": "5001002001",
        "sector": "Distribuição",
        "province": "Luanda",
        "incorporation_date": "2014-03-22",
        "annual_revenue": 4800000,
        "ebitda": 620000,
        "net_income": 250000,
        "total_assets": 3400000,
        "total_liabilities": 1450000,
        "current_assets": 1040000,
        "current_liabilities": 620000,
        "equity": 1950000,
        "cash": 400000,
        "accounts_receivable": 360000,
        "inventory": 280000,
        "accounts_payable": 220000,
        "operating_cash_flow": 720000,
        "capex": 180000,
        "existing_debt": 600000,
        "annual_interest_expense": 75000,
        "annual_debt_service": 360000,
        "requested_amount": 600000,
        "requested_term_months": 24,
        "interest_rate": 12.0,
        "currency": "AOA",
        "purpose": "Capital de giro e expansão de stock.",
        "main_customers": "Supermercados e cadeias locais",
        "top_customer_concentration": 18,
        "import_dependency": 35,
        "foreign_currency_revenue_percentage": 12,
        "foreign_currency_debt_percentage": 8,
        "payment_history": 92,
        "current_overdue_amount": 15000,
        "guarantee_type": "Hipoteca sobre imóveis",
        "guarantee_market_value": 1100000,
        "guarantee_liquidation_value": 820000,
        "guarantee_encumbrance": "nenhum",
        "management_quality": 82,
        "information_quality": 88,
        "sector_risk": 30,
        "circ_status": "bom",
        "compliance_status": "bom",
        "documents_complete": True,
        "expected_drawn_fees": 5000,
        "loan_limit": 0,
        "usage_percentage": 100,
    },
    {
        "company_id": "HCL-002",
        "company_name": "Horizonte Construções, Lda.",
        "nif": "5009803005",
        "sector": "Construção",
        "province": "Benguela",
        "incorporation_date": "2011-10-01",
        "annual_revenue": 6200000,
        "ebitda": 540000,
        "net_income": 120000,
        "total_assets": 4700000,
        "total_liabilities": 2900000,
        "current_assets": 1520000,
        "current_liabilities": 1180000,
        "equity": 1800000,
        "cash": 210000,
        "accounts_receivable": 520000,
        "inventory": 410000,
        "accounts_payable": 290000,
        "operating_cash_flow": 430000,
        "capex": 250000,
        "existing_debt": 980000,
        "annual_interest_expense": 140000,
        "annual_debt_service": 420000,
        "requested_amount": 750000,
        "requested_term_months": 36,
        "interest_rate": 13.5,
        "currency": "AOA",
        "purpose": "Financiamento de obra pública e equipamento.",
        "main_customers": "Contrato X e Cliente Y",
        "top_customer_concentration": 55,
        "import_dependency": 42,
        "foreign_currency_revenue_percentage": 18,
        "foreign_currency_debt_percentage": 22,
        "payment_history": 68,
        "current_overdue_amount": 95000,
        "guarantee_type": "Garantia real e fiança",
        "guarantee_market_value": 1200000,
        "guarantee_liquidation_value": 900000,
        "guarantee_encumbrance": "incerto",
        "management_quality": 74,
        "information_quality": 70,
        "sector_risk": 65,
        "circ_status": "atualizado",
        "compliance_status": "bom",
        "documents_complete": False,
        "expected_drawn_fees": 7000,
        "loan_limit": 0,
        "usage_percentage": 100,
    },
    {
        "company_id": "LIS-003",
        "company_name": "Luanda Import, S.A.",
        "nif": "5004409002",
        "sector": "Importação e distribuição",
        "province": "Luanda",
        "incorporation_date": "2016-02-14",
        "annual_revenue": 9600000,
        "ebitda": 760000,
        "net_income": 180000,
        "total_assets": 5100000,
        "total_liabilities": 3100000,
        "current_assets": 2140000,
        "current_liabilities": 1420000,
        "equity": 2000000,
        "cash": 260000,
        "accounts_receivable": 460000,
        "inventory": 520000,
        "accounts_payable": 350000,
        "operating_cash_flow": 540000,
        "capex": 210000,
        "existing_debt": 1350000,
        "annual_interest_expense": 180000,
        "annual_debt_service": 550000,
        "requested_amount": 900000,
        "requested_term_months": 18,
        "interest_rate": 14.5,
        "currency": "USD",
        "purpose": "Financiamento de stock importado e hedge cambial.",
        "main_customers": "Distribuidores e retalhistas",
        "top_customer_concentration": 28,
        "import_dependency": 75,
        "foreign_currency_revenue_percentage": 25,
        "foreign_currency_debt_percentage": 62,
        "payment_history": 80,
        "current_overdue_amount": 0,
        "guarantee_type": "Garantia de inventário e recebíveis",
        "guarantee_market_value": 1000000,
        "guarantee_liquidation_value": 880000,
        "guarantee_encumbrance": "nenhum",
        "management_quality": 77,
        "information_quality": 82,
        "sector_risk": 58,
        "circ_status": "bom",
        "compliance_status": "bom",
        "documents_complete": True,
        "expected_drawn_fees": 6000,
        "loan_limit": 2000000,
        "usage_percentage": 60,
    },
]


def load_demo_companies() -> list[dict]:
    return DEMO_COMPANIES


def build_demo_form() -> dict:
    return DEMO_COMPANIES[0].copy()
